export const queryKeys = {
  invoices: ['billing', 'invoices'] as const,
  billingSummary: ['billing', 'summary'] as const,
  contractReminders: ['contracts', 'reminders'] as const,
  announcements: ['communications', 'announcements'] as const,
  broadcasts: ['communications', 'broadcasts'] as const,
  communicationsMessages: ['communications', 'messages'] as const,
  broadcastSegments: ['communications', 'broadcast-segments'] as const,
  templates: ['templates'] as const,
  templateMergeTags: ['templates', 'merge-tags'] as const,
  templateTypes: ['templates', 'types'] as const,
  roles: ['admin', 'roles'] as const,
  adminUsers: ['admin', 'users'] as const,
  loginBackground: ['admin', 'login-background'] as const,
  arcRequests: ['arc', 'requests'] as const,
  arcReviewers: ['arc', 'reviewers'] as const,
  elections: ['elections'] as const,
  electionDetail: ['elections', 'detail'] as const,
  electionBallots: ['elections', 'ballots'] as const,
  electionStats: ['elections', 'stats'] as const,
  electionPublic: ['elections', 'public'] as const,
  budgets: ['budgets'] as const,
  budgetDetail: ['budgets', 'detail'] as const,
  notifications: ['notifications', 'all'] as const,
  documents: ['documents', 'tree'] as const,
  meetings: ['meetings'] as const,
  auditLogs: ['audit', 'logs'] as const,
  owners: ['owners', 'all'] as const,
  myOwner: ['owners', 'me'] as const,
  myLinkedOwners: ['owners', 'linked'] as const,
  contracts: ['contracts', 'all'] as const,
  overdueAccounts: ['billing', 'overdue'] as const,
  vendorPayments: ['billing', 'vendor-payments'] as const,
  autopay: ['billing', 'autopay'] as const,
  paperwork: ['paperwork'] as const,
  paperworkFeatures: ['paperwork', 'features'] as const,
};

export type QueryKey = (typeof queryKeys)[keyof typeof queryKeys];
