"""baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-01-07 18:39:24.713773
"""

from alembic import op
import sqlalchemy as sa



revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('grace_period_days', sa.Integer(), nullable=False),
    sa.Column('dunning_schedule_days', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('billing_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_policies_id'), ['id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('termination_notice_deadline', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('attachment_file_name', sa.String(), nullable=True),
    sa.Column('attachment_content_type', sa.String(), nullable=True),
    sa.Column('attachment_file_size', sa.Integer(), nullable=True),
    sa.Column('attachment_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_id'), ['id'], unique=False)

    op.create_table('fine_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('escalation_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('escalation_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('fine_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fine_schedules_id'), ['id'], unique=False)

    op.create_table('notice_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allow_electronic', sa.Boolean(), nullable=False),
    sa.Column('requires_paper', sa.Boolean(), nullable=False),
    sa.Column('default_delivery', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notice_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notice_types_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_notice_types_id'), ['id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_id'), ['id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('late_fee_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('trigger_days_after_grace', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.String(), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fee_percent', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['billing_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('late_fee_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_late_fee_tiers_id'), ['id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('two_factor_secret', sa.String(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('delivery_methods', sa.JSON(), nullable=False),
    sa.Column('recipient_snapshot', sa.JSON(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('sender_snapshot', sa.JSON(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_entity_type', sa.String(), nullable=True),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('bank_balance_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('snapshot_type', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_balance_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_balance_snapshots_id'), ['id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('home_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_year'), ['year'], unique=True)

    op.create_table('communication_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('segment', sa.String(), nullable=True),
    sa.Column('delivery_methods', sa.JSON(), nullable=False),
    sa.Column('recipient_snapshot', sa.JSON(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communication_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_messages_id'), ['id'], unique=False)

    op.create_table('document_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_folders_id'), ['id'], unique=False)

    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elections_id'), ['id'], unique=False)

    op.create_table('email_broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('recipient_snapshot', sa.JSON(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('delivery_methods', sa.JSON(), nullable=False),
    sa.Column('sender_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_broadcasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_broadcasts_id'), ['id'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('zoom_link', sa.String(), nullable=True),
    sa.Column('minutes_file_path', sa.String(), nullable=True),
    sa.Column('minutes_content_type', sa.String(), nullable=True),
    sa.Column('minutes_file_size', sa.Integer(), nullable=True),
    sa.Column('minutes_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_name', sa.String(), nullable=False),
    sa.Column('secondary_name', sa.String(), nullable=True),
    sa.Column('lot', sa.String(), nullable=False),
    sa.Column('property_address', sa.String(), nullable=False),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('primary_email', sa.String(), nullable=True),
    sa.Column('secondary_email', sa.String(), nullable=True),
    sa.Column('primary_phone', sa.String(), nullable=True),
    sa.Column('secondary_phone', sa.String(), nullable=True),
    sa.Column('occupancy_status', sa.String(), nullable=True),
    sa.Column('emergency_contact', sa.String(), nullable=True),
    sa.Column('is_rental', sa.Boolean(), nullable=True),
    sa.Column('lease_document_path', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_by_user_id', sa.Integer(), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('former_lot', sa.String(), nullable=True),
    sa.Column('delivery_preference_global', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['archived_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot')
    )
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owners_delivery_preference_global'), ['delivery_preference_global'], unique=False)
        batch_op.create_index(batch_op.f('ix_owners_id'), ['id'], unique=False)

    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.Column('matched_transactions', sa.Integer(), nullable=False),
    sa.Column('unmatched_transactions', sa.Integer(), nullable=False),
    sa.Column('matched_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unmatched_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliations_id'), ['id'], unique=False)

    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_id'), ['id'], unique=False)

    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('vendor_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('check_number', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_status', sa.String(), nullable=True),
    sa.Column('provider_reference', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_payments_id'), ['id'], unique=False)

    op.create_table('arc_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('final_decision_at', sa.DateTime(), nullable=True),
    sa.Column('final_decision_by_user_id', sa.Integer(), nullable=True),
    sa.Column('decision_notified_at', sa.DateTime(), nullable=True),
    sa.Column('decision_notified_status', sa.String(), nullable=True),
    sa.Column('revision_requested_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['final_decision_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arc_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arc_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_arc_requests_status'), ['status'], unique=False)

    op.create_table('autopay_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_day', sa.Integer(), nullable=False),
    sa.Column('amount_type', sa.String(), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('funding_source_type', sa.String(), nullable=True),
    sa.Column('funding_source_mask', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_payment_method_id', sa.String(), nullable=True),
    sa.Column('provider_status', sa.String(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', name='uq_autopay_owner')
    )
    with op.batch_alter_table('autopay_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autopay_enrollments_id'), ['id'], unique=False)

    op.create_table('budget_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_approvals_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_approvals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_approvals_user_id'), ['user_id'], unique=False)

    op.create_table('budget_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_attachments_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_attachments_id'), ['id'], unique=False)

    op.create_table('budget_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_reserve', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'source_type', 'source_id', name='uq_budget_line_items_source')
    )
    with op.batch_alter_table('budget_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_line_items_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_line_items_id'), ['id'], unique=False)

    op.create_table('election_ballots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('election_ballots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_election_ballots_id'), ['id'], unique=False)

    op.create_table('election_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('election_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_election_candidates_id'), ['id'], unique=False)

    op.create_table('governance_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['document_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('governance_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_governance_documents_id'), ['id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('lot', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('late_fee_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('late_fee_applied', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_late_fee_applied_at', sa.DateTime(), nullable=True),
    sa.Column('last_reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_id'), ['id'], unique=False)

    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('notice_type_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('delivery_channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_email_at', sa.DateTime(), nullable=True),
    sa.Column('mailed_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_method', sa.String(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notice_type_id'], ['notice_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notices_id'), ['id'], unique=False)

    op.create_table('owner_update_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('proposed_changes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner_update_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_update_requests_id'), ['id'], unique=False)

    op.create_table('owner_user_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner_user_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_user_links_id'), ['id'], unique=False)

    op.create_table('reserve_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('inflation_rate', sa.Float(), nullable=False),
    sa.Column('current_funding', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reserve_plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reserve_plan_items_budget_id'), ['budget_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reserve_plan_items_id'), ['id'], unique=False)

    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=False),
    sa.Column('fine_schedule_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('hearing_date', sa.Date(), nullable=True),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['fine_schedule_id'], ['fine_schedules.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_status'), ['status'], unique=False)

    op.create_table('appeals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appeals_id'), ['id'], unique=False)

    op.create_table('arc_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arc_request_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arc_request_id'], ['arc_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arc_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arc_attachments_id'), ['id'], unique=False)

    op.create_table('arc_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arc_request_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['arc_request_id'], ['arc_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arc_conditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arc_conditions_id'), ['id'], unique=False)

    op.create_table('arc_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arc_request_id', sa.Integer(), nullable=False),
    sa.Column('inspector_user_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arc_request_id'], ['arc_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspector_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arc_inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arc_inspections_id'), ['id'], unique=False)

    op.create_table('arc_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arc_request_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arc_request_id'], ['arc_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arc_request_id', 'reviewer_user_id', name='uq_arc_reviews_request_reviewer')
    )
    with op.batch_alter_table('arc_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arc_reviews_id'), ['id'], unique=False)

    op.create_table('election_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('ballot_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('write_in', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ballot_id'], ['election_ballots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['election_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('election_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_election_votes_id'), ['id'], unique=False)

    op.create_table('invoice_late_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['late_fee_tiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_late_fees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_late_fees_id'), ['id'], unique=False)

    op.create_table('paperwork_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('claimed_by_board_member_id', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('mailed_at', sa.DateTime(), nullable=True),
    sa.Column('delivery_method', sa.String(), nullable=True),
    sa.Column('delivery_provider', sa.String(), nullable=True),
    sa.Column('provider_job_id', sa.String(), nullable=True),
    sa.Column('provider_status', sa.String(), nullable=True),
    sa.Column('provider_meta', sa.JSON(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by_board_member_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_id')
    )
    with op.batch_alter_table('paperwork_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paperwork_items_id'), ['id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_received', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)

    op.create_table('violation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violation_messages_id'), ['id'], unique=False)

    op.create_table('violation_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('sent_by_user_id', sa.Integer(), nullable=False),
    sa.Column('notice_type', sa.String(), nullable=False),
    sa.Column('template_key', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violation_notices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violation_notices_id'), ['id'], unique=False)

    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('matched_payment_id', sa.Integer(), nullable=True),
    sa.Column('matched_invoice_id', sa.Integer(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['matched_invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['matched_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['reconciliations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_transactions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transactions_id'))

    op.drop_table('bank_transactions')
    with op.batch_alter_table('violation_notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violation_notices_id'))

    op.drop_table('violation_notices')
    with op.batch_alter_table('violation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violation_messages_id'))

    op.drop_table('violation_messages')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_id'))

    op.drop_table('payments')
    with op.batch_alter_table('paperwork_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paperwork_items_id'))

    op.drop_table('paperwork_items')
    with op.batch_alter_table('invoice_late_fees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_late_fees_id'))

    op.drop_table('invoice_late_fees')
    with op.batch_alter_table('election_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_election_votes_id'))

    op.drop_table('election_votes')
    with op.batch_alter_table('arc_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arc_reviews_id'))

    op.drop_table('arc_reviews')
    with op.batch_alter_table('arc_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arc_inspections_id'))

    op.drop_table('arc_inspections')
    with op.batch_alter_table('arc_conditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arc_conditions_id'))

    op.drop_table('arc_conditions')
    with op.batch_alter_table('arc_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arc_attachments_id'))

    op.drop_table('arc_attachments')
    with op.batch_alter_table('appeals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appeals_id'))

    op.drop_table('appeals')
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violations_status'))
        batch_op.drop_index(batch_op.f('ix_violations_id'))

    op.drop_table('violations')
    with op.batch_alter_table('reserve_plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reserve_plan_items_id'))
        batch_op.drop_index(batch_op.f('ix_reserve_plan_items_budget_id'))

    op.drop_table('reserve_plan_items')
    with op.batch_alter_table('owner_user_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_user_links_id'))

    op.drop_table('owner_user_links')
    with op.batch_alter_table('owner_update_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_update_requests_id'))

    op.drop_table('owner_update_requests')
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notices_id'))

    op.drop_table('notices')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('governance_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_governance_documents_id'))

    op.drop_table('governance_documents')
    with op.batch_alter_table('election_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_election_candidates_id'))

    op.drop_table('election_candidates')
    with op.batch_alter_table('election_ballots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_election_ballots_id'))

    op.drop_table('election_ballots')
    with op.batch_alter_table('budget_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_line_items_id'))
        batch_op.drop_index(batch_op.f('ix_budget_line_items_budget_id'))

    op.drop_table('budget_line_items')
    with op.batch_alter_table('budget_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_attachments_id'))
        batch_op.drop_index(batch_op.f('ix_budget_attachments_budget_id'))

    op.drop_table('budget_attachments')
    with op.batch_alter_table('budget_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_approvals_user_id'))
        batch_op.drop_index(batch_op.f('ix_budget_approvals_id'))
        batch_op.drop_index(batch_op.f('ix_budget_approvals_budget_id'))

    op.drop_table('budget_approvals')
    with op.batch_alter_table('autopay_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autopay_enrollments_id'))

    op.drop_table('autopay_enrollments')
    with op.batch_alter_table('arc_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arc_requests_status'))
        batch_op.drop_index(batch_op.f('ix_arc_requests_id'))

    op.drop_table('arc_requests')
    with op.batch_alter_table('vendor_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_payments_id'))

    op.drop_table('vendor_payments')
    op.drop_table('user_roles')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_id'))

    op.drop_table('templates')
    with op.batch_alter_table('reconciliations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliations_id'))

    op.drop_table('reconciliations')
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owners_id'))
        batch_op.drop_index(batch_op.f('ix_owners_delivery_preference_global'))

    op.drop_table('owners')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_id'))

    op.drop_table('meetings')
    with op.batch_alter_table('email_broadcasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_broadcasts_id'))

    op.drop_table('email_broadcasts')
    with op.batch_alter_table('elections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elections_id'))

    op.drop_table('elections')
    with op.batch_alter_table('document_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_folders_id'))

    op.drop_table('document_folders')
    with op.batch_alter_table('communication_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_messages_id'))

    op.drop_table('communication_messages')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_year'))
        batch_op.drop_index(batch_op.f('ix_budgets_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('bank_balance_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_balance_snapshots_id'))

    op.drop_table('bank_balance_snapshots')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_id'))

    op.drop_table('announcements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    with op.batch_alter_table('late_fee_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_late_fee_tiers_id'))

    op.drop_table('late_fee_tiers')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('notice_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notice_types_id'))
        batch_op.drop_index(batch_op.f('ix_notice_types_code'))

    op.drop_table('notice_types')
    with op.batch_alter_table('fine_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fine_schedules_id'))

    op.drop_table('fine_schedules')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('billing_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_policies_id'))

    op.drop_table('billing_policies')
    # ### end Alembic commands ###
